FROM maven:3.6.3-jdk-11-slim as builder
RUN ls -l 
COPY ./microservices/bigbankservice .
RUN ls -l 
RUN mvn clean package
RUN ls -l 
RUN ls -l target

FROM anapsix/alpine-java:8
WORKDIR /
RUN ls -l
COPY --from=builder /target/bigbankservice-0.0.1-SNAPSHOT.jar /opt/app.jar
RUN ls -l
RUN ls -l
RUN sh -c 'touch /opt/app.jar'
EXPOSE 9090
ENTRYPOINT ["java","-jar","/opt/app.jar"]